env:
  browser: true
  es6: true
  jquery: true
  webextensions: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - mozilla
rules: {}
